# Change these first
owner: chithi-dev # Your GitHub organization or username, where this repository lives
repo: public.chithi.dev # The name of this repository

sites:
    - name: Chithi Public Instance
      url: https://chithi.dev/
    - name: Chithi Valhalla Instance
      url: https://valhalla.chithi.dev/
      
status-website:
    # Add your custom domain name, or remove the `cname` line if you don't have a domain
    # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
    cname: public.chithi.dev
    # baseUrl: /your-repo-name
    logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
    name: Upptime
    introTitle: '**Chithi Monitor** – Keep track of public Chithi instances in real-time'
    introMessage: 'Stay updated with the status of public Chithi instances. View uptime, performance, and issues as they happen.'

    navbar:
        - title: Status
          href: /
        - title: GitHub
          href: https://github.com/$OWNER/$REPO
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
